// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLogMessage(arg1:string):Promise<void>;

export function GetPosition():Promise<{[key: string]: any}>;

export function MoveItem(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function UpdatePosition(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;
