// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLogMessage(arg1) {
  return window['go']['main']['App']['AddLogMessage'](arg1);
}

export function GetPosition() {
  return window['go']['main']['App']['GetPosition']();
}

export function MoveItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MoveItem'](arg1, arg2, arg3, arg4);
}

export function UpdatePosition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdatePosition'](arg1, arg2, arg3, arg4);
}
